// AUTO-GENERATED by scripts/generate-catalog-lastmod.mjs — do not edit by hand.
//
// Per-product (and per-source) last-modified dates for the sitemap, feed.xml
// and llms.txt. `hash` is a sha1 of the source files; `lastmod` moves only
// when that hash changes, so re-running the generator on unchanged sources is
// a no-op. Run it after editing src/data/products or src/data/details (the
// price-sync workflow runs it automatically before committing).

export interface CatalogLastmodEntry {
    hash: string;
    lastmod: string;
}

export const CATALOG_LASTMOD: Record<string, CatalogLastmodEntry> = {
    "anker-310-usb-c-lightning-cable": {
        "hash": "bf540d5fb633a41475fd0dfa6faee390360ac775",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-521-powerhouse": {
        "hash": "881762d02a87e08011244394fc5363c60c7826bf",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-622-maggo": {
        "hash": "f63033818a58c9c4a1dd6932dbe65167489a013d",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-737-powerbank": {
        "hash": "4f5d565e696e01c6afafd02b29e7d857395e533f",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-a1637-wukong-3-in-1-power-bank": {
        "hash": "4f4acdc67a31f19e00767a484f605b49c017a722",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-a2147-gan-charger-30w": {
        "hash": "7611684b88770d1bdbe26f0aa4bc1c01505f7436",
        "lastmod": "2026-10-04T21:29:38.000Z"
    },
    "anker-a2216-magnetic-wireless-car-charger": {
        "hash": "6a4c6cfe3cfb777c3701967242e40a9c511f8f71",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-a2732-charger-35w": {
        "hash": "8eafb48f455a6e13fcc94d427da98aae7904a831",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "anker-a2741-charger-30w": {
        "hash": "d18163ad5c532b844a8d421e330b38b113a7e128",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-a8050-usb-c-cable": {
        "hash": "39ebd092d14a7c148ba1ce6010d853d7f0903e6b",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-car-charger-dual-usb": {
        "hash": "20828bda87dea6dee463cd607723d19933b9f94f",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-nano-45w": {
        "hash": "bcb4a98c7bc19ae4c176edd155a69603f3589d11",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-nano-45w-1c-pd": {
        "hash": "b81729bece19e9dd72cdc6dd31b75b147532c73a",
        "lastmod": "2026-08-01T23:23:49.000Z"
    },
    "anker-nano-45w-smart-display-charger": {
        "hash": "deddce3012fa58bf27d65be3870adc4c33948fef",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-nano-power-bank-a1638-10k-45w": {
        "hash": "197fc68f552f08890230796ce24090d84c395986",
        "lastmod": "2026-08-24T01:29:33.000Z"
    },
    "anker-nano-pro-45w-a2692": {
        "hash": "7505756670d6cf9da892ac9b895f5594ef2d5bf0",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "anker-pencil-stylus": {
        "hash": "b4af3d3d11be29fa13ea073053e1b3992ea5e423",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-powercore-10000": {
        "hash": "1415ba5688886f892076a44793316b5c906bcc63",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-powercore-20000": {
        "hash": "9a27dcba181f0dd5f32f39edff6a1911fcba1c04",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-powercore-26800": {
        "hash": "e503f08a4632937f06f7c1e359bbbac044c6bf50",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-powerline-usb-c-lightning": {
        "hash": "67eee117a00740f0c623cb6b405189a06ef2f530",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-powerline-usb-c-usb-c": {
        "hash": "519d5611fc2db969612fd80f1a2a5dd3b52215dd",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-powerport-20w": {
        "hash": "1f719ce5a0dbd87086f0bf79fe7b74c80bb103a9",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-powerport-25w": {
        "hash": "7b480bd85c4843e0e3041c891302baae05051022",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "anker-powerport-iii-20w-a2639": {
        "hash": "59fdce122fdf483e40a18d9654131820cff60188",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-prime-a1336-20000mah-power-bank": {
        "hash": "9134e4123efd046714dbb30d633d1f9ad7d6338a",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-prime-a1695-25000": {
        "hash": "42e5690c8b5a8691abe72acd1395089ed765ede3",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-prime-a2669-67w-gan-charger": {
        "hash": "b4cf6a89fe6fea4db36177edd808cffc5150b1b5",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-prime-a2688-100w-charger": {
        "hash": "963baf1c491241767513f5c294fe080d172c0529",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "anker-prime-fusion-a1339-9600mah-65w": {
        "hash": "7dff7c4b65345f5a38b94e4cc14ff77529eca224",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "anker-soundcore-flare-2": {
        "hash": "478ad42577282e0c60888cf8293505300aa21fc4",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "anker-soundcore-k20i": {
        "hash": "d0f425f99b70250f124255685836917ba93ff9d3",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-soundcore-life-p2i": {
        "hash": "41ceaee2999443a8eae714e731d2c36582c7418f",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "anker-soundcore-motion-plus": {
        "hash": "f3f811960bdf0e80d64f83b3086109a2c89afd72",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "anker-soundcore-r50i": {
        "hash": "599d463c4437d8de96d8d1c881e224b4b4e72415",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-soundcore-r50i-nc": {
        "hash": "97a6fcb480b298977ba9d76a4d4f02cf171da8cf",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-ultra-soft-usb-c-240w-cable": {
        "hash": "69c863517f05fdf5bdebd8a516cd69839d736b23",
        "lastmod": "2026-08-24T01:29:33.000Z"
    },
    "anker-usb-c-lightning-sureistrong": {
        "hash": "5c0ed37568ce56e7ddf7f3d91fb4fe1f9aa18f88",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "anker-zolo-30w-a2698-charger": {
        "hash": "97f6f112338e7b462701b18ae319739f46f576f9",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-zolo-a110d-10000": {
        "hash": "a00f280960187dd7d72b97d906e74c0c1f2ebbfa",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-zolo-a110e-20000": {
        "hash": "e59aa96956f0c9a4972915dcab940690b2aee163",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "anker-zolo-a1681-20000": {
        "hash": "291f3c906e16fb8a842ea17432090aa9fbc1d844",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "anker-zolo-usb-c-braided-cable": {
        "hash": "152d1589d009a2a93eaf4555b05faae9adec8bc7",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-boombox-3": {
        "hash": "b0eb7fed686e5a9d405fec935c5008004300ce85",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-charge-5": {
        "hash": "ab8ed47fbabac5f70bca6c2e92af0954ba0988bd",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-charge-6": {
        "hash": "b27eb3300e08e5a39880768c944c43572e1f88e4",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-clip-5": {
        "hash": "9922a14f0efe89c47e91e547fb7b1cca6a4f1e74",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-flip-6": {
        "hash": "2be82c1596f82c729a6960a52ecd1251e8bb07bb",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-flip-7": {
        "hash": "33d38f6eb1b892b3af8c62074ca8d76a160016a3",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-go-4": {
        "hash": "2613925b1785794b105402c19172a51a6a5f74b7",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-partybox-1000": {
        "hash": "3bd581a1c8f54f867687cf6b5e3daabe002c5564",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-partybox-club-120": {
        "hash": "01ed2b85c1c60c5c7453e4ba0818e6d21b4b2c48",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-partybox-encore-essential": {
        "hash": "7db40f259d6dc20993de67194ea80d623fb1d6b2",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-partybox-stage-320": {
        "hash": "4213f1051d7c9071eb9ccab9882ac99cef4e7645",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-partybox-wireless-mic": {
        "hash": "1062133899bb75cce114d87824e2d4181aeae2e5",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-pulse-5": {
        "hash": "62487e0535698b9e443272aac38418c7d27b7687",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-t110": {
        "hash": "9f13bac78d638f52251ef0486e1a5e03d299e821",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-t110bt": {
        "hash": "915c3a153955733a8a3289c1c07cc37f239dd723",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-tour-pro-2": {
        "hash": "971f166161bc7b41c7e12b95e681991496e2aa8b",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-tune-520bt": {
        "hash": "56cdfff84e19396d46f603f9402190b82863e232",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-tune-720bt": {
        "hash": "1929cbdfd0b38fc60425daeb1a67e210d02fdeb7",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-tune-770nc": {
        "hash": "515660d33921f6ac2bd7409815464cef689acec9",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-tune-buds": {
        "hash": "3b1a664f2d8a68c0017e97030a435bbca2592573",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-wave-beam": {
        "hash": "fc1d1a297190ba41bfe2ceb8ab714778f6601e78",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "jbl-xtreme-4": {
        "hash": "ba6a42e78949c76e506309b39eb26506574249ea",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-20w-usb-c-charger": {
        "hash": "2c5245f75bf0ce696f215de7b067016c277eaf90",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-25w-fast-charger": {
        "hash": "d993602185cba8445e2005760b4daeb957743ce1",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-3-in-1-data-cable": {
        "hash": "9679e7cebcd039c9fad0aa50df0c81f9b746810d",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "joyroom-3-in-1-wireless-charging-station": {
        "hash": "1675379d3d1d1d4a56bb83253feffcef64dbf0e5",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-30w-fast-charger": {
        "hash": "c774262afea64637472a2eb6812fe2f3c7975bfe",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-30w-pd-cable": {
        "hash": "e3a0134254b5ee3b83014467670672d4240e7fa8",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-60w-car-charger": {
        "hash": "c7f489a7c60f6d872c6c94fe7baf067d965635f2",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-car-mount-zs290": {
        "hash": "9102f67a730fa0b8ce3abfeebdc17f30ca7451d6",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-car-phone-mount": {
        "hash": "7b76ba9444ac56022bf0711969dca2c6d08b82f7",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-ft3-smartwatch": {
        "hash": "75402740ba0c6440a540dbf728ad1631dba4aef3",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-jr-t03-wireless-earbuds": {
        "hash": "a6264b26f87a2cc077c8936b3202d5a6bc13456d",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-jr-x15-pro-stylus-pen": {
        "hash": "4eb8a3ae5ae724a18d9f59dbdb8691eaf5db114a",
        "lastmod": "2026-08-21T15:36:18.000Z"
    },
    "joyroom-magnetic-power-bank-10000": {
        "hash": "d824023370c1430602386b451588702efa40dc66",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "joyroom-power-bank-10000": {
        "hash": "58a09dc23be86337106aade3932ea703ebc37f07",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-power-bank-20000": {
        "hash": "9cf3fbc5e9093bd1e7c0ff9d90f2795e8a73edf2",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "joyroom-t03s-pro-earbuds": {
        "hash": "5abf241cc80b40f5e070ba30276a44b1fdcaef13",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-type-c-lightning-24mos": {
        "hash": "d41052ee8b6de83a45d349c4609708feac4ee877",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "joyroom-type-c-lightning-36mos": {
        "hash": "bd051acc81d7754a2bf709b038a278527da57fdf",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "joyroom-type-c-lightning-braided": {
        "hash": "30124b903e6bc202988dd75165fcecbb63ef9d45",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "joyroom-type-c-to-type-c-cable": {
        "hash": "1491be298e458a4245a83db681db38e2c87554c3",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-usb-a-lightning-1.2m": {
        "hash": "ca1347ceebb49834e84e61a2fff5dd6d0c1c8aa8",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "joyroom-usb-a-lightning-cable": {
        "hash": "5c8ea36d0a008a53f140608d7ee2ad23ec7dd2f9",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "joyroom-usb-a-micro-cable": {
        "hash": "95e74440f07a3e91129ffc41a08c49133ac91f31",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-usb-a-type-c-1.2m": {
        "hash": "3c19ed0893e12e81ee97e16e88280358708ce0e1",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-usb-a-type-c-cable": {
        "hash": "2d072c42b1369f5e89571274045851ea848d4d14",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-usb-c-cable-60w": {
        "hash": "347fd88163962cfa0695e1cf4391de0cab474161",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "joyroom-usb-c-lightning-cable": {
        "hash": "1cfa9ec165898632d30792f5a98a40e6bdd8fe57",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "soundcore-a25i-earbuds": {
        "hash": "cee5398f29019b17dcae0c1e37821012cf510e94",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-a30i-earbuds": {
        "hash": "e5f477cdd3d06e16b27f72421bcbdc7cc1524884",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-c30i-earbuds": {
        "hash": "254d0ca2e00e7f6feb8ada36b512becda97abd39",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-c40i-earbuds": {
        "hash": "217b38a6864636c84d590b0ae81e65e34aa33564",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "soundcore-liberty-3-pro": {
        "hash": "edf93344a404efc24dd8ed3383694d2e050516fc",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "soundcore-liberty-4-nc": {
        "hash": "0ebe42a75548dff423f51d6d78a785c0224ff71b",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-liberty-4-pro": {
        "hash": "fa9a2288a8b61967a8e8a6620385dfd82a73c870",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "soundcore-liberty-5": {
        "hash": "2dd8dbcd10838e49fe50a91c6a6f50cda334b4c7",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-liberty-air-2-pro": {
        "hash": "ede655477b7bf122e3cf7fc8076bd2fa301a6a9a",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "soundcore-liberty-buds": {
        "hash": "e81c9dca6089b1aa9725c59033652ff74dc1ebe6",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-life-q20-headphones": {
        "hash": "4a9018ec796c87994ab7907c4ad29ed48043b542",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-life-u2i-neckband": {
        "hash": "e699296e1c609fa0f2c5c0afd08337c447db0768",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "soundcore-p20i-earbuds": {
        "hash": "51e33cbd048511ddb3b5368ed7ddbf38066e08f3",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-p25i-earbuds": {
        "hash": "bc3cb959c36e7dd7496cea6f5870224b41175beb",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "soundcore-p30i-earbuds": {
        "hash": "f64f2c0ff353c18bc87b5f719b977478ef159839",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-p40i-earbuds": {
        "hash": "8d7459fd82ce7523dffe861957e2edcfbbb02371",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-p41i-earbuds": {
        "hash": "73236c22bc51505f816683eb621796a770b7f607",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-q11i-headphones": {
        "hash": "4d6037240b12531bd0cd49bfb261051f75e8e0b5",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-q20i-headphones": {
        "hash": "ce57d3b5d69ea2844cf0ec956b3b5923802427b3",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-q30-headphones": {
        "hash": "5034d3bbd96c8cfc145cdebef5fef261f7733102",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-q45-headphones": {
        "hash": "08f87a753f8eed8168b1cf62f3eb420cda9b66a1",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-r50i-vi-earbuds": {
        "hash": "43bd341aab455f1736ab20229888a0bf7e2eb27b",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-r60i-nc": {
        "hash": "ec5827933f5b96a52185e16a1e15458b37193ab3",
        "lastmod": "2026-08-10T23:09:03.000Z"
    },
    "soundcore-rave-3-speaker": {
        "hash": "3aa5c434337a51a0bbd71f14110d58e1f06b39c3",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "soundcore-select-4-go-speaker": {
        "hash": "961993f070e6e6efcc0c795ccd23dced6db169da",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "soundcore-space-one-headphones": {
        "hash": "81b6e4943ff809aa9df7e6508c197861ec3730fb",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "soundcore-v20i-earbuds": {
        "hash": "4e7679a4a921ce8d07e290e9be492dcb927c599b",
        "lastmod": "2026-10-04T14:08:40.000Z"
    }
};

export const CATALOG_SOURCE_LASTMOD: Record<string, CatalogLastmodEntry> = {
    "category:anker/accessories": {
        "hash": "40570ad8d8243de9d1471050e164e0c2ca426d7c",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:anker/cables": {
        "hash": "1c2dfa47f6ff6472d3e7d7888d4fa216c7d72b6a",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:anker/car-chargers": {
        "hash": "1256f7dd2d4d5d77c56b331268ebd70ca90d6475",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:anker/power-banks": {
        "hash": "e500b347bc574099a8db8051186dd2ace1b21d10",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:anker/wall-chargers": {
        "hash": "a30661b5a898be2470e26fa4c259bee5881db851",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:jbl/earbuds": {
        "hash": "1ec5dea252b1d09f8f06fa85cbd437fa846b4c92",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:jbl/headphones": {
        "hash": "6058a5d561351b4c21b7fa5e050dbedda73d6719",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:jbl/partybox": {
        "hash": "922604f49c3af8934ba2fc289f4c4d0f6b50a8dd",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:jbl/speakers": {
        "hash": "792acb13397a38fd41fe46e5d3bc56071c453571",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:joyroom/accessories": {
        "hash": "602ce4906b1d63fcf81c98e991a04f1e64352e6c",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:joyroom/audio": {
        "hash": "55b78e63091419c4a45ab2632639a007f2057382",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:joyroom/cables": {
        "hash": "33d0fc84bb173532ac3292c9e45efe5dc5c04db1",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:joyroom/car-accessories": {
        "hash": "37a18e27d08937cff44b88cb20531340ff17a365",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:joyroom/car-chargers": {
        "hash": "be1c3ac5827fb268719256707af99c99dc72c699",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:joyroom/car-holders": {
        "hash": "b77bf0c3713528ccbf77de04be82d3625a999cd7",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:joyroom/power-banks": {
        "hash": "15d7afb5f15c01e1c35ba4a05ceea376fd01e8c8",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:joyroom/smart-watches": {
        "hash": "ba51698737af6c3dcd4b3cbe409c37ec15dee27c",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "category:joyroom/wall-chargers": {
        "hash": "c86bc9ef5931201be1f0cd73b01f9974f61d892e",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:soundcore/audio": {
        "hash": "a783525d79748845431ebce70716d69fd8dbd3e3",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "category:soundcore/speakers": {
        "hash": "32ff0ececfb08ca82e04b80152faa8bb45ed4d24",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "generic:cables": {
        "hash": "cd82109509244119995e637813eb64054d37c141",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "generic:chargers": {
        "hash": "aa4365979b31b0072d24302b26ad6996d2c3f839",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "generic:earbuds": {
        "hash": "6a0cf7358f8984736f5fa1b97b2ba25d4a4acba9",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "generic:power-banks": {
        "hash": "5b70a448e8876e97f6be6a6bac56c9bea617b7aa",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "source:brand-data": {
        "hash": "2c772347b414993885b7165115ef2adef342d420",
        "lastmod": "2026-10-05T01:14:34.000Z"
    },
    "source:faq": {
        "hash": "845f6711139fb09e0d753c0d37df1529dc2879e7",
        "lastmod": "2026-10-04T14:22:47.000Z"
    },
    "source:home": {
        "hash": "e3417c1371d0ba6abe811743234fe197c998fbb6",
        "lastmod": "2026-10-04T14:22:47.000Z"
    },
    "source:locations": {
        "hash": "25dc67b88f110b438c7c41fb107ee8cc8e1a250d",
        "lastmod": "2026-08-11T00:46:02.000Z"
    },
    "source:solutions": {
        "hash": "300b40b2b6fdd1c175f555128f932a602691b3af",
        "lastmod": "2026-10-04T14:08:40.000Z"
    },
    "source:soundcore-hub": {
        "hash": "942db2c8af8526a8ea7b8f8d8de3b1691534fc05",
        "lastmod": "2026-10-05T01:14:34.000Z"
    }
};
