// AUTO-GENERATED by scripts/generate-client-catalog.mjs — DO NOT EDIT MANUALLY.
// Slim, description-free catalog that is safe to ship in client bundles.
// Source of truth: src/data/products/*.ts (via src/data/seed-products.ts).
// Regenerate: node scripts/generate-client-catalog.mjs

/** Slim variant — pricing facts only. */
export interface ClientCatalogVariant {
    id: string;
    sku: string;
    price: number;
    stock: number;
    isDefault?: boolean;
}

/** Slim product — pricing/bundle/cart fields only (never descriptions). */
export interface ClientCatalogProduct {
    slug: string;
    sku: string;
    brand: string;
    categorySlug: string;
    price: number;
    originalPrice: number;
    stock: number;
    featured: boolean;
    status: string;
    translations: { en: { name: string }; ar: { name: string } };
    image?: { url: string; alt: string };
    variants?: ClientCatalogVariant[];
}

export const clientCatalog: ClientCatalogProduct[] = [
    {
        "slug": "anker-soundcore-motion-plus",
        "sku": "SH07",
        "brand": "Soundcore",
        "categorySlug": "speakers",
        "price": 3600,
        "originalPrice": 4279,
        "stock": 793,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Soundcore Motion+ | 30W Hi-Res Audio"
            },
            "ar": {
                "name": "سماعة انكر ساوندكور Motion+ | سماعة تجمعات الرووف والساحل اللي مبتفصلش"
            }
        },
        "image": {
            "url": "/products/anker/anker-soundcore-motion-plus/anker-soundcore-motion-plus-package-box-contents-cable.webp",
            "alt": "محتويات علبة سماعة ساوندكور موشن بلس مع كابل وملحقات - كايرو فولت مصر"
        }
    },
    {
        "slug": "anker-soundcore-flare-2",
        "sku": "SS02",
        "brand": "Soundcore",
        "categorySlug": "speakers",
        "price": 2999,
        "originalPrice": 3569,
        "stock": 629,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Soundcore Flare 2 | 360° Sound & LED Light Show"
            },
            "ar": {
                "name": "مكبر صوت انكر ساوندكور Flare 2 | سماعة السهرة بإضاءة LED بتتفاعل مع الموسيقى"
            }
        },
        "image": {
            "url": "/products/anker/anker-soundcore-flare-2/anker-soundcore-flare-2-ipx7-waterproof-pool-outdoor.webp",
            "alt": "سماعة ساوندكور فلير 2 مقاومة للماء IPX7 - استخدام حمام سباحة وأماكن مفتوحة - كايرو فولت"
        }
    },
    {
        "slug": "anker-737-powerbank",
        "sku": "AP02",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 4999,
        "originalPrice": 5780,
        "stock": 412,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker 737 Power Bank (PowerCore 24K, A1289011) | Listed 140W PD 3.1 | 24,000mAh"
            },
            "ar": {
                "name": "باور بانك انكر 737 (A1289011) | بروفايلات PD 3.1 مدرجة حتى 140 واط | 24,000 مللي أمبير"
            }
        },
        "image": {
            "url": "/products/anker/anker-737-powerbank/anker-737-powercore-24000mah-140w-premium-power-bank-cairovolt.webp",
            "alt": "باور بانك انكر 737 بقوة 140 واط 24000 مللي أمبير بريميوم - كايرو فولت مصر"
        }
    },
    {
        "slug": "anker-622-maggo",
        "sku": "AP04",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 2800,
        "originalPrice": 3309,
        "stock": 457,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker 622 Magnetic Battery (MagGo) | MagSafe | Foldable Stand"
            },
            "ar": {
                "name": "باور بانك انكر 622 MagGo للايفون | بستاند مدمج"
            }
        },
        "image": {
            "url": "/products/anker/anker-622-maggo/anker-622-maggo-package-box-contents-cable-egypt.webp",
            "alt": "محتويات علبة انكر 622 ماج جو مع كابل USB-C - كايرو فولت مصر"
        }
    },
    {
        "slug": "anker-521-powerhouse",
        "sku": "AP01",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 11000,
        "originalPrice": 12830,
        "stock": 727,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker 521 PowerHouse 256Wh | 200W AC Outlet | LiFePO4"
            },
            "ar": {
                "name": "محطة طاقة انكر 521 بسعة 256Wh | خرج AC بقدرة 200 واط | LiFePO4"
            }
        },
        "image": {
            "url": "/products/anker/anker-521-powerhouse/anker-521-powerhouse-usb-c-60w-pd-output-port-detail.webp",
            "alt": "Anker 521 Powerhouse LCD display showing battery percentage and wattage - CairoVolt"
        },
        "variants": [
            {
                "id": "anker-521",
                "sku": "ANK-PB-521",
                "price": 11000,
                "stock": 1950,
                "isDefault": true
            },
            {
                "id": "anker-522",
                "sku": "ANK-PH-522",
                "price": 22000,
                "stock": 2180
            },
            {
                "id": "anker-535",
                "sku": "ANK-PH-535",
                "price": 36000,
                "stock": 1920
            }
        ]
    },
    {
        "slug": "anker-powercore-10000",
        "sku": "AP09",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 1300,
        "originalPrice": 1469,
        "stock": 871,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker PowerCore 10000mAh Power Bank"
            },
            "ar": {
                "name": "باور بانك انكر PowerCore 10000 مللي أمبير موديل A1263"
            }
        },
        "image": {
            "url": "/products/anker/anker-powercore-10000/anker-powercore-10000-size-comparison-hand-pocket-portable.webp",
            "alt": "Anker PowerCore 10000 size comparison with hand - pocket-friendly portable design - CairoVolt"
        }
    },
    {
        "slug": "anker-powercore-20000",
        "sku": "AP08",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 1550,
        "originalPrice": 1899,
        "stock": 1177,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker PowerCore 20000mAh | 72Wh | Dual USB-A"
            },
            "ar": {
                "name": "باور بانك انكر PowerCore بسعة 20000 مللي أمبير | 72Wh | منفذا USB-A"
            }
        },
        "image": {
            "url": "/products/anker/anker-powercore-20000/anker-powercore-20000-charging-samsung-galaxy-compatible.webp",
            "alt": "Anker PowerCore 20000 LED 4-light battery indicator showing remaining charge level - CairoVolt"
        }
    },
    {
        "slug": "anker-powercore-26800",
        "sku": "AP05",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 2300,
        "originalPrice": 2630,
        "stock": 1485,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker PowerCore III Elite 26K 60W PD | Laptop Charging"
            },
            "ar": {
                "name": "باور بانك انكر PowerCore III Elite 26K | USB-C PD حتى 60 واط"
            }
        },
        "image": {
            "url": "/products/anker/anker-powercore-26800/anker-powercore-26800mah-ultra-capacity-power-bank-cairovolt.webp",
            "alt": "باور بانك انكر PowerCore III Elite 26K سعة 25,600 مللي أمبير بخرج USB-C PD بقوة 60 واط - كايرو فولت مصر"
        }
    },
    {
        "slug": "anker-powerport-20w",
        "sku": "AC04",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 490,
        "originalPrice": 560,
        "stock": 1146,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker A2347K11 20W USB-C PD Charger | Check Device Profile and Plug"
            },
            "ar": {
                "name": "شاحن انكر A2347K11 بحد معلن 20 واط USB-C PD | راجع بروفايل الجهاز والقابس والضمان"
            }
        },
        "image": {
            "url": "/products/anker/anker-powerport-20w/anker-powerport-20w-usb-c-pd-wall-charger-cairovolt-egypt.webp",
            "alt": "شاحن انكر 20 واط USB-C PD حائطي صغير الحجم - كايرو فولت مصر"
        }
    },
    {
        "slug": "anker-powerport-25w",
        "sku": "AC02",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 550,
        "originalPrice": 640,
        "stock": 1179,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker 25W PPS Charger (A2322K11) | Samsung-Compatible USB-C PD"
            },
            "ar": {
                "name": "شاحن انكر 25 واط PPS (A2322K11) | USB-C PD متوافق مع موديلات سامسونج المدعومة"
            }
        },
        "image": {
            "url": "/products/anker/anker-powerport-25w/anker-powerport-25w-usb-c-port-detail-pps-protocol.webp",
            "alt": "Anker 25W USB-C port with PPS protocol for Samsung Super Fast Charging detail - CairoVolt"
        }
    },
    {
        "slug": "anker-nano-45w",
        "sku": "AC01",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 790,
        "originalPrice": 949,
        "stock": 464,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Nano 45W GaN USB-C Charger | MacBook Air + iPhone 17"
            },
            "ar": {
                "name": "شاحن انكر نانو 45 واط | شاحن واحد للابتوب والموبايل (وداعاً للزحمة)"
            }
        },
        "image": {
            "url": "/products/anker/anker-nano-45w/anker-nano-45w-package-box-contents-specifications.webp",
            "alt": "محتويات علبة شاحن انكر نانو 45 واط مع المواصفات - كايرو فولت مصر"
        }
    },
    {
        "slug": "anker-nano-45w-smart-display-charger",
        "sku": "AR01",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 1900,
        "originalPrice": 2340,
        "stock": 450,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Nano 45W Smart Display GaN Charger (A121D) | 180° Foldable Plug | USB-C PD"
            },
            "ar": {
                "name": "شاحن انكر نانو 45 واط بشاشة ذكية (A121D) | قابس 180° | USB-C PD"
            }
        },
        "image": {
            "url": "/products/anker/anker-nano-45w-smart-display-charger/anker-nano-45w-smart-display-charger-front-180-foldable-white-cairovolt.webp",
            "alt": "Anker Nano 45W Smart Display charger A121D front view with 180° foldable plug and Hi greeting animation on TFT screen - CairoVolt"
        }
    },
    {
        "slug": "anker-powerline-usb-c-lightning",
        "sku": "AK01",
        "brand": "Anker",
        "categorySlug": "cables",
        "price": 630,
        "originalPrice": 759,
        "stock": 452,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker PowerLine Select USB-C to Lightning (A8612H11) | Verify MFi | USB-PD"
            },
            "ar": {
                "name": "كابل انكر PowerLine Select من USB-C إلى Lightning (A8612H11) | تحقق من MFi | USB-PD"
            }
        },
        "image": {
            "url": "/products/anker/anker-powerline-usb-c-lightning/anker-powerline-usb-c-lightning-braided-nylon-durable.webp",
            "alt": "نسيج نايلون مضفر لكابل انكر باور لاين - متانة وجودة عالية - كايرو فولت"
        }
    },
    {
        "slug": "anker-powerline-usb-c-usb-c",
        "sku": "AK03",
        "brand": "Anker",
        "categorySlug": "cables",
        "price": 590,
        "originalPrice": 700,
        "stock": 1409,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker PowerLine III USB-C to USB-C | 60W | iPhone 17 & Samsung S26"
            },
            "ar": {
                "name": "كابل انكر USB-C إلى USB-C بقدرة حتى 60 واط | راجع الضمان الحالي"
            }
        },
        "image": {
            "url": "/products/anker/anker-powerline-usb-c-usb-c/anker-powerline-usb-c-to-usb-c-100w-cable-cairovolt-egypt.webp",
            "alt": "كابل انكر USB-C إلى USB-C 60 واط متين - كايرو فولت مصر"
        }
    },
    {
        "slug": "anker-car-charger-dual-usb",
        "sku": "AR02",
        "brand": "Anker",
        "categorySlug": "car-chargers",
        "price": 950,
        "originalPrice": 1080,
        "stock": 525,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker PowerDrive 2 Car Charger | 24W Dual USB | PowerIQ"
            },
            "ar": {
                "name": "شاحن سيارة انكر (منفذين) | بيشحن موبايلين وانت عالق في زحمة الدائري"
            }
        },
        "image": {
            "url": "/products/anker/anker-car-charger-dual-usb/anker-car-charger-dual-usb-package-box-contents-egypt.webp",
            "alt": "Anker dual USB car charger package box and contents - CairoVolt Egypt"
        }
    },
    {
        "slug": "joyroom-power-bank-10000",
        "sku": "JP01",
        "brand": "Joyroom",
        "categorySlug": "power-banks",
        "price": 1624,
        "originalPrice": 1969,
        "stock": 462,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom 10000mAh Slim Power Bank | Dual USB | LED Display"
            },
            "ar": {
                "name": "باور بانك جوي روم 10000 مللي | الفئة الاقتصادية (منقذ الطلبة)"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-power-bank-10000/joyroom-joyroom-power-bank-10000-egypt-cairo-1.webp",
            "alt": "باور بانك جوي روم 10000 في مصر - موديل JR-T012 - كايرو فولت"
        }
    },
    {
        "slug": "joyroom-power-bank-20000",
        "sku": "JP02",
        "brand": "Joyroom",
        "categorySlug": "power-banks",
        "price": 997,
        "originalPrice": 1189,
        "stock": 1254,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom 20000mAh Power Bank | 22.5W PD+QC | Triple Output"
            },
            "ar": {
                "name": "باور بانك جوي روم 20000 | ثلاثة مخارج وشاشة LED | راجع الشروط الحالية"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-power-bank-20000/joyroom-joyroom-power-bank-20000-egypt-cairo-1.webp",
            "alt": "Joyroom JR-T020 20000mAh power bank main view - CairoVolt"
        }
    },
    {
        "slug": "joyroom-t03s-pro-earbuds",
        "sku": "JH02",
        "brand": "Joyroom",
        "categorySlug": "audio",
        "price": 664,
        "originalPrice": 799,
        "stock": 579,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom T03S Pro ANC Earbuds | 30H Battery | Bluetooth 5.3"
            },
            "ar": {
                "name": "سماعة جوي روم T03S Pro | ANC وBluetooth 5.3"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-t03s-pro-earbuds/joyroom-joyroom-t03s-pro-earbuds-egypt-cairo-1.webp",
            "alt": "joyroom t03s pro earbuds - product listing in Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-jr-t03-wireless-earbuds",
        "sku": "JH01",
        "brand": "Joyroom",
        "categorySlug": "audio",
        "price": 774,
        "originalPrice": 910,
        "stock": 564,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom JR-T03 Wireless Earbuds | 20H Battery | Bluetooth 5.0"
            },
            "ar": {
                "name": "سماعة جوي روم JR-T03 | بلوتوث 5.0 وتحكم باللمس"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-jr-t03-wireless-earbuds/joyroom-joyroom-jr-t03-wireless-earbuds-egypt-cairo-1.webp",
            "alt": "Joyroom JR-T03 wireless earbuds and charging case main view - CairoVolt"
        }
    },
    {
        "slug": "joyroom-20w-usb-c-charger",
        "sku": "JC03",
        "brand": "Joyroom",
        "categorySlug": "wall-chargers",
        "price": 236,
        "originalPrice": 290,
        "stock": 919,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom 20W USB-C PD Charger | iPhone 17 Fast Charge"
            },
            "ar": {
                "name": "شاحن جوي روم JR-TCF20 بقدرة 20 واط PD | USB-C"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-20w-usb-c-charger/joyroom-joyroom-20w-usb-c-charger-egypt-cairo-1.webp",
            "alt": "Joyroom 20W USB-C charger JR-TCF20 product view - CairoVolt Egypt"
        }
    },
    {
        "slug": "joyroom-usb-c-lightning-cable",
        "sku": "JK08",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 118,
        "originalPrice": 140,
        "stock": 447,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom USB-C to Lightning Cable | Listed 20W PD | Braided"
            },
            "ar": {
                "name": "كابل جوي روم USB-C إلى Lightning | قدرة معلنة حتى 20 واط | مضفر"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-usb-c-lightning-cable/joyroom-joyroom-usb-c-lightning-cable-egypt-cairo-1.webp",
            "alt": "joyroom usb c lightning cable - product listing in Egypt - CairoVolt"
        }
    },
    {
        "slug": "anker-soundcore-life-p2i",
        "sku": "SH23",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 820,
        "originalPrice": 950,
        "stock": 566,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Soundcore Life P2i | 28H Battery | AI Calls | Bluetooth 5.2"
            },
            "ar": {
                "name": "سماعات انكر ساوندكور Life P2i | 28 ساعة ومكالمات AI"
            }
        },
        "image": {
            "url": "/products/anker/anker-soundcore-life-p2i/anker-soundcore-life-p2i-wireless-earbuds-10mm-cairovolt.webp",
            "alt": "سماعات ساوندكور لايف P2i لاسلكية درايفر 10mm - كايرو فولت مصر"
        }
    },
    {
        "slug": "joyroom-ft3-smartwatch",
        "sku": "JW02",
        "brand": "Joyroom",
        "categorySlug": "smart-watches",
        "price": 1092,
        "originalPrice": 1239,
        "stock": 629,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom FT3 Smartwatch | Manufacturer-Listed IP68, Sports Modes and Heart-Rate Sensor"
            },
            "ar": {
                "name": "ساعة جوي روم FT3 | IP68 وأوضاع رياضية ومستشعر نبض معلنة من الشركة | الضمان الحالي"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-ft3-smartwatch/joyroom-joyroom-ft3-smartwatch-egypt-cairo-1.webp",
            "alt": "joyroom ft3 smartwatch - product view | CairoVolt Egypt"
        }
    },
    {
        "slug": "joyroom-car-mount-zs290",
        "sku": "JR01",
        "brand": "Joyroom",
        "categorySlug": "car-holders",
        "price": 934,
        "originalPrice": 1089,
        "stock": 451,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom Magnetic Car Mount ZS290 | N52 Magnets | MagSafe | 360°"
            },
            "ar": {
                "name": "حامل موبايل مغناطيسي جوي روم ZS290 | MagSafe ومفصل 360° | راجع الشروط الحالية"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-car-mount-zs290/joyroom-joyroom-car-mount-zs290-egypt-cairo-1.webp",
            "alt": "Joyroom JR-ZS290 magnetic air-vent car phone mount front view - CairoVolt"
        }
    },
    {
        "slug": "joyroom-25w-fast-charger",
        "sku": "JC01",
        "brand": "Joyroom",
        "categorySlug": "wall-chargers",
        "price": 342,
        "originalPrice": 410,
        "stock": 1058,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom 25W USB-C PD Charger (JR-TCF25) | iPhone and Samsung Compatibility"
            },
            "ar": {
                "name": "شاحن جوي روم 25 واط USB-C PD موديل JR-TCF25 | توافق ايفون وسامسونج"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-25w-fast-charger/joyroom-joyroom-25w-fast-charger-egypt-cairo-3.webp",
            "alt": "Joyroom 25W Fast Charger - product package view - CairoVolt"
        }
    },
    {
        "slug": "joyroom-30w-fast-charger",
        "sku": "JC02",
        "brand": "Joyroom",
        "categorySlug": "wall-chargers",
        "price": 280,
        "originalPrice": 340,
        "stock": 1261,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom 30W PD+QC Wall Charger | Dual USB-C and USB-A Ports"
            },
            "ar": {
                "name": "شاحن جوي روم 30 واط PD+QC | منفذا USB-C وUSB-A"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-30w-fast-charger/joyroom-joyroom-30w-fast-charger-egypt-cairo-1.webp",
            "alt": "Joyroom 30W PD and QC fast charger in Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-magnetic-power-bank-10000",
        "sku": "JP03",
        "brand": "Joyroom",
        "categorySlug": "power-banks",
        "price": 850,
        "originalPrice": 1019,
        "stock": 758,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom MagSafe Power Bank 10000mAh | 15W Wireless + 20W Wired | Kickstand"
            },
            "ar": {
                "name": "باور بانك جوي روم JR-W030 مغناطيسي 10000 مللي أمبير | حامل مدمج"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-magnetic-power-bank-10000/joyroom-joyroom-magnetic-power-bank-10000-egypt-cairo-1.webp",
            "alt": "Joyroom Magnetic MagSafe Power Bank 10000mAh Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-60w-car-charger",
        "sku": "JK01",
        "brand": "Joyroom",
        "categorySlug": "car-chargers",
        "price": 513,
        "originalPrice": 599,
        "stock": 637,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom JR-CL26 Retractable Car Charger | Verify 60W-Class Output"
            },
            "ar": {
                "name": "شاحن سيارة جوي روم JR-CL26 بكابل قابل للسحب | تحقق من قدرة فئة 60 واط"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-60w-car-charger/joyroom-joyroom-60w-car-charger-egypt-cairo-6.webp",
            "alt": "Joyroom JR-CL26 retractable car charger - CairoVolt"
        }
    },
    {
        "slug": "joyroom-3-in-1-wireless-charging-station",
        "sku": "JW01",
        "brand": "Joyroom",
        "categorySlug": "wall-chargers",
        "price": 1206,
        "originalPrice": 1480,
        "stock": 416,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom 3-in-1 MagSafe Station | iPhone 17 + Apple Watch + AirPods | 15W | Aluminum"
            },
            "ar": {
                "name": "محطة شحن جوي روم 3 في 1 | كومودينو رايق بدون كركبة سلوك"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-3-in-1-wireless-charging-station/joyroom-joyroom-3-in-1-wireless-charging-station-egypt-cairo-1.webp",
            "alt": "Joyroom 3-in-1 Wireless Charging Station Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-3-in-1-data-cable",
        "sku": "JH03",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 237,
        "originalPrice": 280,
        "stock": 413,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom 3-in-1 Multi-Connector Charging Cable"
            },
            "ar": {
                "name": "كابل جوي روم 3 في 1 بموصلات Lightning وUSB-C وMicro-USB"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-3-in-1-data-cable/joyroom-joyroom-3-in-1-data-cable-egypt-cairo-1.webp",
            "alt": "Joyroom JR-S-1830G 3-in-1 Lightning USB-C and Micro-USB cable"
        }
    },
    {
        "slug": "joyroom-car-phone-mount",
        "sku": "JR02",
        "brand": "Joyroom",
        "categorySlug": "car-holders",
        "price": 169,
        "originalPrice": 200,
        "stock": 619,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom Car Phone Mount | Verify Phone and Vehicle Fit"
            },
            "ar": {
                "name": "حامل موبايل للسيارة جوي روم JR-ZS295 | دليل المقاس والتركيب"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-car-phone-mount/joyroom-joyroom-car-phone-mount-egypt-cairo-1.webp",
            "alt": "Joyroom Car Phone Mount Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-usb-c-cable-60w",
        "sku": "JK07",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 123,
        "originalPrice": 140,
        "stock": 452,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom 60W USB-C to USB-C Fast Charging Cable"
            },
            "ar": {
                "name": "كابل جوي روم 60 واط USB-C | انسى كابلات العتبة اللي بتتقطع بعد أسبوع | نايلون متين"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-usb-c-cable-60w/joyroom-joyroom-usb-c-cable-60w-egypt-cairo-1.webp",
            "alt": "Joyroom 60W USB-C Cable iPhone 17 Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-type-c-lightning-braided",
        "sku": "JK02",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 214,
        "originalPrice": 249,
        "stock": 481,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom USB-C to Lightning Braided Cable"
            },
            "ar": {
                "name": "كابل جوي روم USB-C إلى Lightning | كابل ايفون نايلون مضاد للقطع"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-type-c-lightning-braided/joyroom-joyroom-type-c-lightning-braided-egypt-cairo-1.webp",
            "alt": "Joyroom Type-C Lightning Braided Cable Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-30w-pd-cable",
        "sku": "JK10",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 94,
        "originalPrice": 110,
        "stock": 1391,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom 30W PD Fast Charging Cable 1.2m"
            },
            "ar": {
                "name": "كابل جوي روم 30 واط PD بطول 1.2 متر | USB-C إلى USB-C"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-30w-pd-cable/joyroom-joyroom-30w-pd-cable-egypt-cairo-1.webp",
            "alt": "Joyroom 30W PD Cable Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-usb-a-lightning-cable",
        "sku": "JK12",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 43,
        "originalPrice": 50,
        "stock": 542,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom USB-A to Lightning Cable 1m"
            },
            "ar": {
                "name": "كابل جوي روم USB-A إلى Lightning بطول مدرج 1 متر"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-usb-a-lightning-cable/joyroom-joyroom-usb-a-lightning-cable-egypt-cairo-1.webp",
            "alt": "Joyroom USB-A Lightning Cable Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-type-c-to-type-c-cable",
        "sku": "JK05",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 130,
        "originalPrice": 149,
        "stock": 616,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom USB-C to USB-C Cable JR-S-CC100"
            },
            "ar": {
                "name": "كابل جوي روم USB-C إلى USB-C موديل JR-S-CC100"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-type-c-to-type-c-cable/joyroom-joyroom-type-c-to-type-c-cable-egypt-cairo-1.webp",
            "alt": "Joyroom JR-S-CC100 USB-C to USB-C cable - CairoVolt"
        }
    },
    {
        "slug": "joyroom-usb-a-micro-cable",
        "sku": "JH04",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 44,
        "originalPrice": 50,
        "stock": 479,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom USB-A to Micro USB Cable 1.2m"
            },
            "ar": {
                "name": "كابل جوي روم USB-A إلى Micro USB 1.2 متر | كابل السماعات والباور بانك القديم"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-usb-a-micro-cable/joyroom-joyroom-usb-a-micro-cable-egypt-cairo-1.webp",
            "alt": "Joyroom USB-A Micro Cable Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-usb-a-type-c-cable",
        "sku": "JK11",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 86,
        "originalPrice": 100,
        "stock": 572,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom USB-A to Type-C Cable 1m"
            },
            "ar": {
                "name": "كابل جوي روم USB-A إلى Type-C 1 متر | وصل شاحنك القديم بموبايلك الجديد"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-usb-a-type-c-cable/joyroom-joyroom-usb-a-type-c-cable-egypt-cairo-1.webp",
            "alt": "Joyroom USB-A Type-C Cable Egypt - CairoVolt"
        }
    },
    {
        "slug": "anker-usb-c-lightning-sureistrong",
        "sku": "AK02",
        "brand": "Anker",
        "categorySlug": "cables",
        "price": 599,
        "originalPrice": 730,
        "stock": 511,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker SureIStrong USB-C to Lightning Cable"
            },
            "ar": {
                "name": "كابل انكر SureIStrong USB-C إلى Lightning | كابل ايفون الفاخر اللي مبيتشابكش ومبيتبقعش"
            }
        },
        "image": {
            "url": "/products/anker/anker-usb-c-lightning-sureistrong/anker-usb-c-lightning-sureistrong-240w-braided-cable-cairovolt.webp",
            "alt": "Anker SureIStrong USB-C to Lightning PD braided cable with Kevlar reinforcement - CairoVolt Egypt"
        }
    },
    {
        "slug": "joyroom-type-c-lightning-24mos",
        "sku": "JK06",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 123,
        "originalPrice": 140,
        "stock": 542,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom JR-S-CL24M USB-C to Lightning Cable"
            },
            "ar": {
                "name": "كابل جوي روم JR-S-CL24M من USB-C إلى Lightning"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-type-c-lightning-24mos/joyroom-joyroom-type-c-lightning-24mos-egypt-cairo-2.webp",
            "alt": "Joyroom JR-S-CL24M USB-C to Lightning cable packaging - CairoVolt"
        }
    },
    {
        "slug": "joyroom-type-c-lightning-36mos",
        "sku": "JK04",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 131,
        "originalPrice": 150,
        "stock": 403,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Joyroom JR-S-CL36M USB-C to Lightning Cable | Braided Exterior"
            },
            "ar": {
                "name": "كابل جوي روم USB-C إلى Lightning (JR-S-CL36M) | راجع مدة وشروط الضمان الحالية"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-type-c-lightning-36mos/joyroom-joyroom-type-c-lightning-36mos-egypt-cairo-1.webp",
            "alt": "Joyroom JR-S-CL36M USB-C to Lightning cable packaging - CairoVolt"
        }
    },
    {
        "slug": "joyroom-usb-a-type-c-1.2m",
        "sku": "JK03",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 214,
        "originalPrice": 249,
        "stock": 510,
        "featured": false,
        "status": "retired",
        "translations": {
            "en": {
                "name": "Joyroom USB-A to Type-C Cable 1.2m (4ft)"
            },
            "ar": {
                "name": "كابل جوي روم JR-S-AC12 من USB-A إلى USB-C بطول 1.2 متر | راجع التيار والبيانات"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-usb-a-type-c-1.2m/joyroom-joyroom-usb-a-type-c-1.2m-egypt-cairo-1.webp",
            "alt": "Joyroom USB-A Type-C 1.2m Cable Egypt - CairoVolt"
        }
    },
    {
        "slug": "joyroom-usb-a-lightning-1.2m",
        "sku": "JK09",
        "brand": "Joyroom",
        "categorySlug": "cables",
        "price": 114,
        "originalPrice": 140,
        "stock": 574,
        "featured": false,
        "status": "retired",
        "translations": {
            "en": {
                "name": "Joyroom USB-A to Lightning Cable 1.2m (4ft)"
            },
            "ar": {
                "name": "كابل جوي روم JR-S-AL12 من USB-A إلى Lightning بطول 1.2 متر"
            }
        },
        "image": {
            "url": "/products/joyroom/joyroom-usb-a-lightning-1.2m/joyroom-joyroom-usb-a-lightning-1.2m-egypt-cairo-1.webp",
            "alt": "Joyroom USB-A Lightning 1.2m Cable Egypt - CairoVolt"
        }
    },
    {
        "slug": "anker-zolo-a110d-10000",
        "sku": "AP10",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 1270,
        "originalPrice": 1450,
        "stock": 956,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker ZOLO Power Bank 10,000mAh (22.5W) | Built-in Cable"
            },
            "ar": {
                "name": "باور بانك انكر زولو 10,000 مللي أمبير (22.5 واط) | كابل مدمج"
            }
        },
        "image": {
            "url": "/products/anker/anker-zolo-a110d-10000/anker-zolo-a110d-10000mah-power-bank-builtin-usb-c-cable-led-display-cairovolt.webp",
            "alt": "Anker ZOLO A110D 10000mAh power bank with built-in USB-C cable and LED digital display - CairoVolt Egypt"
        }
    },
    {
        "slug": "anker-zolo-a110e-20000",
        "sku": "AP07",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 1730,
        "originalPrice": 1959,
        "stock": 779,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker ZOLO Power Bank 20,000mAh (22.5W) | Built-in Cable"
            },
            "ar": {
                "name": "باور بانك انكر زولو 20,000 مللي أمبير (22.5 واط) | كابل مدمج"
            }
        },
        "image": {
            "url": "/products/anker/anker-zolo-a110e-20000/anker-zolo-a110e-20000mah-power-bank-builtin-cable-dual-output-cairovolt.webp",
            "alt": "Anker ZOLO A110E power bank 20000mAh front view with built-in USB-C cable - Egypt - CairoVolt"
        }
    },
    {
        "slug": "anker-zolo-a1681-20000",
        "sku": "AP06",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 2200,
        "originalPrice": 2609,
        "stock": 544,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker ZOLO Power Bank 20,000mAh 30W | Built-In Dual Cables"
            },
            "ar": {
                "name": "باور بانك انكر زولو 20,000 مللي أمبير 30 واط | كابلان مدمجان"
            }
        },
        "image": {
            "url": "/products/anker/anker-zolo-a1681-20000/anker-zolo-a1681-dual-port-output-detail-usb-c-pd-specification.webp",
            "alt": "Anker ZOLO A1681 built-in USB-C 30W and Lightning 27W cables with USB-A port detail - CairoVolt"
        }
    },
    {
        "slug": "anker-prime-a1695-25000",
        "sku": "AP03",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 3950,
        "originalPrice": 4750,
        "stock": 746,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Zolo Power Bank 25,000mAh 165W — Built-In Dual Cables | MacBook Charging"
            },
            "ar": {
                "name": "باور بانك انكر زولو 25,000 مللي أمبير 165 واط — كابلان مدمجان | شحن ماك بوك"
            }
        },
        "image": {
            "url": "/products/anker/anker-prime-a1695-25000/anker-prime-a1695-25000mah-165w-power-bank-premium-cairovolt.webp",
            "alt": "Anker Prime A1695 power bank 25000mAh 165W front view - Egypt - CairoVolt"
        }
    },
    {
        "slug": "anker-a2732-charger-35w",
        "sku": "AR03",
        "brand": "Anker",
        "categorySlug": "car-chargers",
        "price": 550,
        "originalPrice": 659,
        "stock": 407,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker PowerDrive PD+ 2 Car Charger 35W (A2732) | USB-C PD + USB-A"
            },
            "ar": {
                "name": "شاحن سيارة انكر PowerDrive PD+ 2 بقوة 35 واط (A2732) | USB-C PD + USB-A"
            }
        },
        "image": {
            "url": "/products/anker/anker-a2732-charger-35w/anker-a2732-35w-dual-usb-c-charger-pd-compact-design-cairovolt.webp",
            "alt": "Anker A2732 PowerDrive PD+ 2 car charger 35W plugged into car cigarette lighter - CairoVolt"
        }
    },
    {
        "slug": "anker-a2741-charger-30w",
        "sku": "AR04",
        "brand": "Anker",
        "categorySlug": "car-chargers",
        "price": 530,
        "originalPrice": 630,
        "stock": 812,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker 30W Mini Car Charger (A2741) | USB-C 30W PD + USB-A 22.5W | Ultra-Compact"
            },
            "ar": {
                "name": "شاحن سيارة انكر 30 واط ميني (A2741) | USB-C 30 واط PD/PPS + USB-A 22.5 واط | فائق الصغر"
            }
        },
        "image": {
            "url": "/products/anker/anker-a2741-charger-30w/anker-a2741-30w-dual-port-charger-usb-c-usb-a-cairovolt.webp",
            "alt": "Anker A2741 car charger 30W USB-C PD and USB-A in car cigarette lighter socket - CairoVolt"
        }
    },
    {
        "slug": "anker-a8050-usb-c-cable",
        "sku": "AK04",
        "brand": "Anker",
        "categorySlug": "cables",
        "price": 570,
        "originalPrice": 680,
        "stock": 540,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker USB-A to USB-C Cable (A8050) | Braided Nylon 1.8m | Fast Charging"
            },
            "ar": {
                "name": "كابل انكر USB-A إلى USB-C مضفر 1.8 متر (A8050) | شحن سريع"
            }
        },
        "image": {
            "url": "/products/anker/anker-a8050-usb-c-cable/anker-a8050-braided-nylon-cable-texture-close-up-durability.webp",
            "alt": "Anker A8050 USB-C connector detail reinforced stress point - CairoVolt"
        }
    },
    {
        "slug": "anker-soundcore-k20i",
        "sku": "SH26",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 750,
        "originalPrice": 849,
        "stock": 847,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Soundcore K20i | 13mm Drivers | 36h Battery | Semi-In-Ear"
            },
            "ar": {
                "name": "سماعة انكر ساوندكور K20i | 13mm درايفر | 36 ساعة بطارية | نصف داخلية"
            }
        },
        "image": {
            "url": "/products/anker/anker-soundcore-k20i/anker-soundcore-k20i-wireless-earbuds-charging-case-cairovolt.webp",
            "alt": "Soundcore K20i true wireless earbuds semi-in-ear - Egypt - CairoVolt"
        }
    },
    {
        "slug": "anker-soundcore-r50i-nc",
        "sku": "SH21",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 1199,
        "originalPrice": 1440,
        "stock": 812,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore R50i NC A3959 Earbuds | Manufacturer-Listed ANC and Battery | Phone-Stand Case"
            },
            "ar": {
                "name": "سماعة ساوندكور R50i NC موديل A3959 | عزل وبطارية معلنان من الشركة | علبة بحامل | الضمان الحالي"
            }
        },
        "image": {
            "url": "/products/anker/anker-soundcore-r50i-nc/anker-soundcore-r50i-nc-earbud-anc-driver-detail-closeup.webp",
            "alt": "سماعة ساوندكور R50i NC مع إلغاء ضوضاء - كايرو فولت"
        }
    },
    {
        "slug": "anker-soundcore-r50i",
        "sku": "SH22",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 880,
        "originalPrice": 1050,
        "stock": 856,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Soundcore R50i | 10mm Drivers | 30h Battery | In-Ear"
            },
            "ar": {
                "name": "سماعة انكر ساوندكور R50i | 10mm درايفر | 30 ساعة | داخلية"
            }
        },
        "image": {
            "url": "/products/anker/anker-soundcore-r50i/anker-soundcore-r50i-wireless-earbuds-10mm-driver-cairovolt.webp",
            "alt": "Soundcore R50i wireless earbuds 10mm BassUp drivers - product view in Egypt - CairoVolt"
        }
    },
    {
        "slug": "anker-a2147-gan-charger-30w",
        "sku": "AC03",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 490,
        "originalPrice": 589,
        "stock": 1127,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker 511 Nano 3 GaN Charger 30W (A2147) | USB-C PD | IQ3"
            },
            "ar": {
                "name": "شاحن انكر 511 نانو 3 GaN بقوة 30 واط (A2147) | USB-C PD | IQ3"
            }
        },
        "image": {
            "url": "/products/anker/anker-a2147-gan-charger-30W/anker-a2147-nano3-30w-gan-charger-usb-c-front-cairovolt.webp",
            "alt": "Anker A2147 Nano 3 GaN 30W USB-C wall charger with foldable plug and IQ3 technology - CairoVolt"
        }
    },
    {
        "slug": "soundcore-p20i-earbuds",
        "sku": "SH28",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 699,
        "originalPrice": 790,
        "stock": 709,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore P20i | 10mm Drivers | 30h Battery | Bluetooth 5.3"
            },
            "ar": {
                "name": "سماعة ساوندكور P20i | 10mm درايفر | 30 ساعة بطارية | بلوتوث 5.3"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-p20i-earbuds/soundcore-p20i-earbuds-main-view-cairovolt.webp",
            "alt": "Soundcore P20i A3949Z11 main view - CairoVolt"
        }
    },
    {
        "slug": "soundcore-p25i-earbuds",
        "sku": "SH25",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 770,
        "originalPrice": 899,
        "stock": 1089,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore P25i | 10mm BassUp | 30h Battery | Ultra-Light"
            },
            "ar": {
                "name": "سماعة ساوندكور P25i | 10mm BassUp | 30 ساعة بطارية | خفيفة جداً"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-p25i-earbuds/soundcore-p25i-earbuds-main-view-cairovolt.webp",
            "alt": "Soundcore P25i A3949 main view - CairoVolt"
        }
    },
    {
        "slug": "soundcore-liberty-4-nc",
        "sku": "SH09",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 2570,
        "originalPrice": 3090,
        "stock": 1176,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Liberty 4 NC | Manufacturer-Listed Adaptive ANC | 11mm | LDAC | Up to 50h"
            },
            "ar": {
                "name": "سماعة ساوندكور ليبرتي 4 NC | عزل تكيفي معلن | 11mm | LDAC | حتى 50 ساعة"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-liberty-4-nc/soundcore-liberty-4-nc-features-angle-cairovolt.webp",
            "alt": "سماعة ساوندكور ليبرتي 4 NC لاسلكية عزل ضوضاء - A3947 - كايرو فولت"
        }
    },
    {
        "slug": "soundcore-a30i-earbuds",
        "sku": "SH18",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 1450,
        "originalPrice": 1699,
        "stock": 719,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore A30i | 46dB Smart ANC | 6mm | 24h Battery | Lipstick Case | BT 5.4"
            },
            "ar": {
                "name": "سماعة ساوندكور A30i | 46dB ANC ذكي | 6mm | 24 ساعة | علبة ليبستيك | BT 5.4"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-a30i-earbuds/soundcore-a30i-earbuds-main-view-cairovolt.webp",
            "alt": "Soundcore A30i A3958 lipstick case compact ANC earbuds - CairoVolt"
        }
    },
    {
        "slug": "soundcore-liberty-5",
        "sku": "SH06",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 3997,
        "originalPrice": 4630,
        "stock": 856,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Liberty 5 | 9.2mm Wool-Paper Driver | Adaptive ANC 3.0 | IP55 | LDAC | Up to 48h"
            },
            "ar": {
                "name": "سماعة ساوندكور ليبرتي 5 | درايفر 9.2mm | عزل ANC 3.0 | IP55 | LDAC | حتى 48 ساعة"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-liberty-5/soundcore-liberty-5-main-view-cairovolt.webp",
            "alt": "Soundcore Liberty 5 wireless earbuds 9.2mm wool-paper driver Adaptive ANC 3.0 LDAC - product view in Egypt - CairoVolt"
        }
    },
    {
        "slug": "soundcore-liberty-4-pro",
        "sku": "SH01",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 5830,
        "originalPrice": 6870,
        "stock": 806,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Liberty 4 Pro | ACAA Dual Driver | Adaptive ANC 3.0 | Smart Case | LDAC | 40h"
            },
            "ar": {
                "name": "سماعة ساوندكور ليبرتي 4 برو | درايفر ACAA مزدوج | عزل تكيفي 3.0 | علبة ذكية | LDAC | 40 ساعة"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-liberty-4-pro/soundcore-liberty-4-pro-main-view-cairovolt.webp",
            "alt": "Soundcore Liberty 4 Pro wireless earbuds ACAA dual driver 10.5mm Hi-Res LDAC - product view in Egypt - CairoVolt"
        }
    },
    {
        "slug": "soundcore-p30i-earbuds",
        "sku": "SH21",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 1200,
        "originalPrice": 1440,
        "stock": 1092,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore P30i | 42dB ANC | 10mm BassUp | 45h Battery | Phone Stand Case | BT 5.4"
            },
            "ar": {
                "name": "سماعة ساوندكور P30i | عزل ضوضاء 42dB | 10mm BassUp | 45 ساعة | علبة ستاند | BT 5.4"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-p30i-earbuds/soundcore-p30i-earbuds-main-view-cairovolt.webp",
            "alt": "Soundcore P30i A3959 main view - CairoVolt"
        }
    },
    {
        "slug": "soundcore-life-q20-headphones",
        "sku": "SH13",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 2350,
        "originalPrice": 2879,
        "stock": 796,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Life Q20 | 40mm Hi-Res | ANC | 60h Battery | Over-Ear"
            },
            "ar": {
                "name": "سماعة ساوندكور Life Q20 | 40mm Hi-Res | عزل ضوضاء | 60 ساعة | هيدفون"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-life-q20-headphones/soundcore-life-q20-headphones-main-view-cairovolt.webp",
            "alt": "Soundcore Life Q20 A3025 main view - CairoVolt"
        }
    },
    {
        "slug": "soundcore-liberty-buds",
        "sku": "SH17",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 1750,
        "originalPrice": 2119,
        "stock": 751,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Liberty Buds | Semi-In-Ear | ANC 3.0 | 11mm LDAC | BT 6.1 | 30h"
            },
            "ar": {
                "name": "سماعة ساوندكور Liberty Buds | Semi-In-Ear | ANC 3.0 | 11mm LDAC | BT 6.1 | 30 ساعة"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-liberty-buds/soundcore-liberty-buds-main-view-cairovolt.webp",
            "alt": "Soundcore Liberty Buds A3960 semi-in-ear wireless earbuds ANC 3.0 - CairoVolt"
        }
    },
    {
        "slug": "soundcore-liberty-air-2-pro",
        "sku": "SH15",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 2150,
        "originalPrice": 2459,
        "stock": 997,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Liberty Air 2 Pro | LDAC Hi-Res | ANC | 11mm PureNote | Qi | HearID | 26h"
            },
            "ar": {
                "name": "سماعة ساوندكور Liberty Air 2 Pro | LDAC Hi-Res | ANC | 11mm PureNote | Qi | HearID | 26 ساعة"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-liberty-air-2-pro/soundcore-liberty-air-2-pro-main-view-cairovolt.webp",
            "alt": "Soundcore Liberty Air 2 Pro A3951 ANC LDAC Qi - CairoVolt"
        }
    },
    {
        "slug": "soundcore-p40i-earbuds",
        "sku": "SH16",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 2052,
        "originalPrice": 2459,
        "stock": 811,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore P40i | Adaptive ANC | 11mm BassUp | 60h Battery | App EQ"
            },
            "ar": {
                "name": "سماعة ساوندكور P40i | ANC تكيّفي | 11mm BassUp | 60 ساعة | علبة حامل موبايل"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-p40i-earbuds/soundcore-p40i-earbuds-main-view-cairovolt.webp",
            "alt": "Soundcore P40i A3955 main view - CairoVolt"
        }
    },
    {
        "slug": "soundcore-p41i-earbuds",
        "sku": "SH11",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 2439,
        "originalPrice": 2860,
        "stock": 1070,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore P41i | Adaptive ANC | 11mm BassUp | 192h Battery | 3,000mAh Powerbank Case | BT 5.3"
            },
            "ar": {
                "name": "سماعة ساوندكور P41i | ANC تكيّفي | 11mm BassUp | 192 ساعة | علبة باور بانك 3,000mAh | BT 5.3"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-p41i-earbuds/soundcore-p41i-earbuds-main-view-cairovolt.webp",
            "alt": "Soundcore P41i A3937 travel earbuds 192h battery powerbank case - CairoVolt"
        }
    },
    {
        "slug": "soundcore-v20i-earbuds",
        "sku": "SH19",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 1449,
        "originalPrice": 1699,
        "stock": 792,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore V20i | Open-Ear Ear-Hook | 16mm BassUp | 36h | LED | IP55 | BT 5.3"
            },
            "ar": {
                "name": "سماعة ساوندكور V20i | خطاف أذن مفتوح | 16mm BassUp | 36 ساعة | LED | IP55 | BT 5.3"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-v20i-earbuds/soundcore-v20i-earbuds-main-view-cairovolt.webp",
            "alt": "Soundcore V20i A3876 open-ear ear-hook 16mm BassUp - CairoVolt"
        }
    },
    {
        "slug": "soundcore-r50i-vi-earbuds",
        "sku": "SH24",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 785,
        "originalPrice": 900,
        "stock": 992,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore R50i Vi | AI Voice | 10mm BassUp | 30h | Bluetooth 5.3"
            },
            "ar": {
                "name": "سماعة ساوندكور R50i Vi | ذكاء اصطناعي صوتي | 10mm BassUp | 30 ساعة"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-r50i-vi-earbuds/soundcore-r50i-vi-earbuds-main-view-cairovolt.webp",
            "alt": "Soundcore R50i Vi A3969 main view - CairoVolt"
        }
    },
    {
        "slug": "soundcore-life-u2i-neckband",
        "sku": "SH27",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 739,
        "originalPrice": 869,
        "stock": 957,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Life U2i | Neckband | 10mm Graphene BassUp | 22h | IPX5 | BT 5.0"
            },
            "ar": {
                "name": "سماعة ساوندكور Life U2i | نيكباند | 10mm جرافين BassUp | 22 ساعة | IPX5 | BT 5.0"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-life-u2i-neckband/soundcore-life-u2i-neckband-main-view-cairovolt.webp",
            "alt": "Soundcore Life U2i A3213 neckband 10mm graphene BassUp - CairoVolt"
        }
    },
    {
        "slug": "soundcore-c30i-earbuds",
        "sku": "SH12",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 2350,
        "originalPrice": 2679,
        "stock": 1120,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore C30i | Open-Ear Clip-On | 12×17mm Titanium | 30h Battery | BT 5.3"
            },
            "ar": {
                "name": "سماعة ساوندكور C30i | كليب أذن مفتوح | 12×17mm تيتانيوم | 30 ساعة | BT 5.3"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-c30i-earbuds/soundcore-c30i-earbuds-main-view-cairovolt.webp",
            "alt": "Soundcore C30i A3330 open-ear clip-on earbuds - CairoVolt"
        }
    },
    {
        "slug": "soundcore-c40i-earbuds",
        "sku": "SH08",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 3050,
        "originalPrice": 3559,
        "stock": 1045,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore C40i | Open-Ear Clip-On | A3331"
            },
            "ar": {
                "name": "سماعة ساوندكور C40i كليب أذن مفتوح | موديل A3331"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-c40i-earbuds/soundcore-c40i-earbuds-main-view-cairovolt.webp",
            "alt": "Soundcore C40i A3331 open-ear clip-on titanium flex - CairoVolt"
        }
    },
    {
        "slug": "soundcore-liberty-3-pro",
        "sku": "SH05",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 4400,
        "originalPrice": 5199,
        "stock": 820,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Liberty 3 Pro | 10.6mm ACAA 2.0 Dual-Driver | HearID ANC | LDAC | Wireless Charging | 32h"
            },
            "ar": {
                "name": "سماعة ساوندكور Liberty 3 Pro | درايفر 10.6mm ACAA 2.0 مزدوج | HearID ANC | LDAC | شحن لاسلكي | 32 ساعة"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-liberty-3-pro/soundcore-liberty-3-pro-main-view-cairovolt.webp",
            "alt": "Soundcore Liberty 3 Pro A3952 main view - CairoVolt"
        }
    },
    {
        "slug": "soundcore-q30-headphones",
        "sku": "SH04",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 4649,
        "originalPrice": 5379,
        "stock": 740,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Life Q30 | Hybrid ANC 3 Modes | 40mm Silk Driver | 40h ANC / 60h Off | Foldable"
            },
            "ar": {
                "name": "سماعة ساوندكور Q30 | عزل هجين 3 أوضاع | 40mm درايفر حرير | 40 ساعة ANC / 60 بدون | قابل للطي"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-q30-headphones/soundcore-q30-headphones-main-view-cairovolt.webp",
            "alt": "Soundcore Life Q30 over-ear headphones 40mm hybrid ANC 3 modes 60h battery - product view in Egypt - CairoVolt"
        }
    },
    {
        "slug": "soundcore-q45-headphones",
        "sku": "SH03",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 4685,
        "originalPrice": 5559,
        "stock": 829,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Space Q45 | Adaptive ANC | 40mm Drivers | LDAC | Long Battery Life"
            },
            "ar": {
                "name": "سماعة ساوندكور سبيس Q45 | عزل تكيفي | درايفر 40mm | LDAC"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-q45-headphones/soundcore-q45-headphones-main-view-cairovolt.webp",
            "alt": "Soundcore Space Q45 over-ear headphones 40mm silk driver 98% ANC LDAC - product view in Egypt - CairoVolt"
        }
    },
    {
        "slug": "soundcore-q11i-headphones",
        "sku": "SH14",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 2312,
        "originalPrice": 2710,
        "stock": 813,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Q11i | 40mm BassUp | 60h Battery | Foldable | Multipoint BT 5.3"
            },
            "ar": {
                "name": "سماعة ساوندكور Q11i | 40mm BassUp | 60 ساعة | قابل للطي | BT 5.3 Multipoint"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-q11i-headphones/soundcore-q11i-headphones-main-view-cairovolt.webp",
            "alt": "Soundcore Q11i A3005 over-ear 40mm BassUp foldable - CairoVolt"
        }
    },
    {
        "slug": "soundcore-q20i-headphones",
        "sku": "SH10",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 2522,
        "originalPrice": 3070,
        "stock": 939,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Q20i | Hybrid ANC | 40mm Driver | Multipoint | Wired Input"
            },
            "ar": {
                "name": "سماعة ساوندكور Q20i | عزل هجين | درايفر 40mm | اتصال متعدد | مدخل سلكي"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-q20i-headphones/soundcore-q20i-headphones-main-view-cairovolt.webp",
            "alt": "Soundcore Q20i budget ANC over-ear headphones 40mm 60h battery - product view in Egypt - CairoVolt"
        }
    },
    {
        "slug": "soundcore-space-one-headphones",
        "sku": "SH02",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 4700,
        "originalPrice": 5469,
        "stock": 1031,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Space One | Adaptive ANC | 40mm Driver | LDAC | 40h ANC / 55h Off | Foldable"
            },
            "ar": {
                "name": "سماعة ساوندكور سبيس ون | عزل تكيفي | 40mm درايفر | LDAC | 40 ساعة ANC / 55 بدون | قابل للطي"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-space-one-headphones/soundcore-space-one-headphones-main-view-cairovolt.webp",
            "alt": "Soundcore Space One over-ear headphones 40mm adaptive ANC LDAC 55h battery - product view in Egypt - CairoVolt"
        }
    },
    {
        "slug": "soundcore-rave-3-speaker",
        "sku": "SS01",
        "brand": "Soundcore",
        "categorySlug": "speakers",
        "price": 9450,
        "originalPrice": 11359,
        "stock": 719,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Rave 3 | 200W | 6.5\" Woofer | AI Karaoke | 2 Wireless Mics | HexaGlow | 12h | IPX4"
            },
            "ar": {
                "name": "مكبر صوت ساوندكور Rave 3 | 200 واط | ووفر 6.5\" | كاريوكي AI | 2 مايك لاسلكي | HexaGlow | 12 ساعة | IPX4"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-rave-3-speaker/soundcore-rave-3-speaker-main-view-cairovolt.webp",
            "alt": "Soundcore Rave 3 A31A3 200W party karaoke speaker - CairoVolt"
        }
    },
    {
        "slug": "soundcore-select-4-go-speaker",
        "sku": "SS03",
        "brand": "Soundcore",
        "categorySlug": "speakers",
        "price": 1249,
        "originalPrice": 1470,
        "stock": 927,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Soundcore Select 4 Go A31X1 | Manufacturer-Listed IP67 and Floating Design | 5W"
            },
            "ar": {
                "name": "مكبر صوت ساوندكور Select 4 Go A31X1 | تصنيف IP67 وتصميم طافٍ معلنان | 5 واط | الضمان الحالي"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-select-4-go-speaker/soundcore-select-4-go-speaker-main-view-cairovolt.webp",
            "alt": "Soundcore Select 4 Go A31X1 IP67 waterproof floating speaker - CairoVolt"
        }
    },
    {
        "slug": "anker-pencil-stylus",
        "sku": "AA01",
        "brand": "Anker",
        "categorySlug": "accessories",
        "price": 1199,
        "originalPrice": 1389,
        "stock": 750,
        "featured": true,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Pencil Pro A7166 | iPad Stylus | Tilt | Palm Rejection | Magnetic Charging"
            },
            "ar": {
                "name": "قلم انكر Pencil Pro A7166 للايباد | ميل ورفض لمس الكف | شحن مغناطيسي"
            }
        },
        "image": {
            "url": "/products/anker/anker-pencil-stylus/anker-pencil-stylus-main-view-cairovolt.webp",
            "alt": "Anker Pencil Pro A7166 iPad stylus tilt sensitivity palm rejection magnetic - product view in Egypt - CairoVolt"
        }
    },
    {
        "slug": "anker-a1637-wukong-3-in-1-power-bank",
        "sku": "AP13",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 2999,
        "originalPrice": 3559,
        "stock": 281,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker x Black Myth: Wukong 3-in-1 Power Bank (A1637) — Built-in Cable + Foldable AC Plug | 10000mAh 30W GaN"
            },
            "ar": {
                "name": "انكر × بلاك ميث ووكونج باور بانك 3 في 1 (A1637) — كابل مدمج + فيشة بتتطوى | 10000 مللي أمبير 30 واط GaN"
            }
        },
        "image": {
            "url": "/products/anker/anker-a1637-wukong-3-in-1-power-bank/anker-a1637-wukong-3-in-1-power-bank-hero-front-display-plug-cable.webp",
            "alt": "Anker A1637 Wukong 3-in-1 power bank, gold LED display, red braided cable & foldable plug — كايرو فولت"
        }
    },
    {
        "slug": "anker-310-usb-c-lightning-cable",
        "sku": "AK06",
        "brand": "Anker",
        "categorySlug": "cables",
        "price": 730,
        "originalPrice": 839,
        "stock": 271,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker 310 USB-C to Lightning (A81A5) | Verify MFi, USB-PD and Bend-Test Listing"
            },
            "ar": {
                "name": "كابل انكر 310 من USB-C إلى لايتننج (A81A5) | تحقق من MFi وUSB-PD واختبار الثني"
            }
        },
        "image": {
            "url": "/products/anker/anker-310-usb-c-lightning-cable/anker-310-usb-c-lightning-cable-usb-c-lightning-connectors-hero.webp",
            "alt": "كابل انكر 310 USB-C إلى لايتننج مضفّر أسود - Anker 310 braided USB-C to Lightning cable connectors - كايرو فولت"
        }
    },
    {
        "slug": "anker-nano-45w-1c-pd",
        "sku": "AC09",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 775,
        "originalPrice": 899,
        "stock": 222,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Nano 45W 1C (A2664) — Single-Port USB-C GaN | iPhone 17 & MacBook Air"
            },
            "ar": {
                "name": "شاحن انكر نانو 45 واط 1C (A2664) | منفذ USB-C واحد بتقنية GaN"
            }
        },
        "image": {
            "url": "/products/anker/anker-nano-45w-1c-pd/anker-nano-45w-1c-pd-main-front-hero-white.webp",
            "alt": "شاحن انكر نانو 45 واط أبيض بمنفذ USB-C وشعار PD - Anker Nano 45W single USB-C PD wall charger - كايرو فولت"
        }
    },
    {
        "slug": "anker-nano-pro-45w-a2692",
        "sku": "AC08",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 790,
        "originalPrice": 970,
        "stock": 291,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Nano Pro A2692 45W USB-C GaN Charger — Single Port | Check PD/PPS Profiles"
            },
            "ar": {
                "name": "شاحن انكر نانو برو A2692 بحد معلن 45 واط USB-C GaN | راجع بروفايلات PD/PPS والضمان الحالي"
            }
        },
        "image": {
            "url": "/products/anker/anker-nano-pro-45w-a2692/anker-nano-pro-45w-a2692-angled-hero-black-charger.webp",
            "alt": "Anker Nano Pro 45W USB-C charger A2692 angled hero, black GaN wall plug with IQ3 badge — CairoVolt"
        }
    },
    {
        "slug": "anker-a2216-magnetic-wireless-car-charger",
        "sku": "AR05",
        "brand": "Anker",
        "categorySlug": "car-chargers",
        "price": 1200,
        "originalPrice": 1480,
        "stock": 125,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Nano Magnetic Wireless Car Charger (A2216) | Qi2 15W | 14N Bendable Dashboard Mount"
            },
            "ar": {
                "name": "شاحن انكر نانو المغناطيسي اللاسلكي للسيارة (A2216) | Qi2 حتى 15 واط | حامل تابلوه مرن"
            }
        },
        "image": {
            "url": "/products/anker/anker-a2216-magnetic-wireless-car-charger/anker-a2216-magnetic-wireless-car-charger-full-kit-hero-white.webp",
            "alt": "Anker Nano A2216 magnetic wireless car charger kit with USB-C car adapter and cable — كايرو فولت"
        }
    },
    {
        "slug": "anker-powerport-iii-20w-a2639",
        "sku": "AC04",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 520,
        "originalPrice": 620,
        "stock": 247,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker PowerPort III 20W Cube A2149P21 — USB-C PD | Check Device Profile"
            },
            "ar": {
                "name": "شاحن انكر باور بورت III 20 واط كيوب — USB-C شحن سريع للايفون"
            }
        },
        "image": {
            "url": "/products/anker/anker-powerport-iii-20w-a2639/anker-powerport-iii-20w-a2639-main-hero-front-usb-c.webp",
            "alt": "Anker PowerPort III 20W Cube A2149 شاحن حائط USB-C PD أبيض واجهة أمامية - كايرو فولت"
        }
    },
    {
        "slug": "anker-prime-a2688-100w-charger",
        "sku": "AC06",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 1999,
        "originalPrice": 2439,
        "stock": 276,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Prime A2688 100W 3-Port GaN Charger — 2 USB-C + 1 USB-A | Check Port Allocation"
            },
            "ar": {
                "name": "شاحن انكر برايم A2688 بقدرة إجمالية معلنة 100 واط GaN و3 منافذ | راجع توزيع الطاقة والضمان الحالي"
            }
        },
        "image": {
            "url": "/products/anker/anker-prime-a2688-100w-charger/anker-prime-a2688-100w-charger-angled-hero-three-ports.webp",
            "alt": "Anker Prime A2688 100W GaN 3-port charger, 2 USB-C + 1 USB-A, angled view - شاحن انكر برايم 100 واط | CairoVolt"
        }
    },
    {
        "slug": "anker-prime-a1336-20000mah-power-bank",
        "sku": "AP11",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 5900,
        "originalPrice": 6799,
        "stock": 254,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Prime 20,000mAh Power Bank (A1336) — 200W 3-in-1 | Dual 100W USB-C"
            },
            "ar": {
                "name": "انكر برايم باور بانك 20000mAh (A1336) — 200 واط 3 في 1 | منفذين USB-C 100 واط"
            }
        },
        "image": {
            "url": "/products/anker/anker-prime-a1336-20000mah-power-bank/anker-prime-a1336-20000mah-power-bank-angled-hero-smart-display.webp",
            "alt": "Anker Prime A1336 باور بانك 20000mAh 200W بشاشة ذكية تعرض 88% - CairoVolt"
        }
    },
    {
        "slug": "anker-prime-a2669-67w-gan-charger",
        "sku": "AC07",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 1970,
        "originalPrice": 2330,
        "stock": 313,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Prime 67W GaN Wall Charger (A2669) — 3 Ports (2 USB-C + USB-A) | GaNPrime + PowerIQ 4.0"
            },
            "ar": {
                "name": "شاحن حائط انكر برايم 67 واط جان (A2669) — 3 منافذ (2 USB-C + USB-A) | GaNPrime وPowerIQ 4.0"
            }
        },
        "image": {
            "url": "/products/anker/anker-prime-a2669-67w-gan-charger/anker-prime-a2669-67w-gan-charger-angled-hero-3-port-front.webp",
            "alt": "Anker Prime 67W GaN charger A2669, 3 ports (2 USB-C + USB-A) — شاحن انكر برايم جان — كايرو فولت"
        }
    },
    {
        "slug": "anker-prime-fusion-a1339-9600mah-65w",
        "sku": "AP12",
        "brand": "Anker",
        "categorySlug": "power-banks",
        "price": 3200,
        "originalPrice": 3609,
        "stock": 209,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Prime Power Bank 9,600mAh 65W Fusion (A1339) | Hybrid Charger + Foldable Plug"
            },
            "ar": {
                "name": "انكر برايم باور بانك فيوجن 9,600 مللي أمبير 65 واط (A1339) | شاحن هجين بقابس قابل للطي"
            }
        },
        "image": {
            "url": "/products/anker/anker-prime-fusion-a1339-9600mah-65w/anker-prime-fusion-a1339-9600mah-65w-main-front-hero-plug-inset.webp",
            "alt": "Anker Prime Fusion A1339 power bank 9,600mAh 65W, smart display at 88% with foldable US plug inset — CairoVolt"
        }
    },
    {
        "slug": "soundcore-a25i-earbuds",
        "sku": "SH29",
        "brand": "Soundcore",
        "categorySlug": "audio",
        "price": 1370,
        "originalPrice": 1540,
        "stock": 293,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Soundcore A25i — 10mm BassUp Drivers | 28h Battery | IPX5"
            },
            "ar": {
                "name": "سماعة انكر ساوندكور A25i | درايفر 10mm BassUp | بطارية معلنة 28 ساعة | IPX5 | راجع الضمان"
            }
        },
        "image": {
            "url": "/products/anker/soundcore-a25i-earbuds/soundcore-a25i-earbuds-earbuds-case-lanyard-hero.webp",
            "alt": "سماعات Anker Soundcore A25i اللاسلكية مع علبة الشحن وحبل التعليق باللون الأسود - كايرو فولت"
        }
    },
    {
        "slug": "anker-zolo-30w-a2698-charger",
        "sku": "AC10",
        "brand": "Anker",
        "categorySlug": "wall-chargers",
        "price": 599,
        "originalPrice": 680,
        "stock": 179,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Zolo 30W USB-C Wall Charger (A2698) | GaN + Ultra-low Temperature | Foldable Plug"
            },
            "ar": {
                "name": "شاحن حائط انكر زولو 30 واط USB-C (A2698) | GaN وقابس قابل للطي"
            }
        },
        "image": {
            "url": "/products/anker/anker-zolo-30w-a2698-charger/anker-zolo-30w-a2698-charger-hero-front-foldable-plug.webp",
            "alt": "شاحن انكر زولو 30 وات A2698 بمنفذ USB-C وقابس قابل للطي - Anker Zolo 30W USB-C charger, CairoVolt"
        }
    },
    {
        "slug": "anker-zolo-usb-c-braided-cable",
        "sku": "AK05",
        "brand": "Anker",
        "categorySlug": "cables",
        "price": 790,
        "originalPrice": 919,
        "stock": 151,
        "featured": false,
        "status": "active",
        "translations": {
            "en": {
                "name": "Anker Zolo USB-C to USB-C Braided Cable (A8060) — 240W PD 3.1, 1.5m | 240W-Grade 8-Core Wire"
            },
            "ar": {
                "name": "كابل انكر زولو USB-C إلى USB-C مضفر (A8060) — 240 واط PD 3.1، 1.5 متر | سلك 8 نوى بمعمار 240 واط"
            }
        },
        "image": {
            "url": "/products/anker/anker-zolo-usb-c-braided-cable/anker-zolo-usb-c-braided-cable-dual-usb-c-connectors-hero.webp",
            "alt": "Anker Zolo USB-C to USB-C braided cable, silver aluminum connectors and white braid — CairoVolt"
        }
    }
];
